### PR TITLE
Migrating the existing meeting notes from the hackmd over to files in…

### PR DESCRIPTION
**Pull request by karenhchu**
… the community repo

Signed-off-by: Karen Chu <karen.chu@microsoft.com>

### CODE REVIEW

**Comment by karenhchu** [comment]
I need to make a change to the file but it looks like I don't have permissions. What should I do? Should I just make another pull request afterwards?

**Comment by radu-matei** [comment]
I suspect you are trying to modify the file from the GitHub UI, but the URL is of an absolute commit, rather than of the branch.
If you go to the desired file on the branch (https://github.com/karenhchu/cnab-community/blob/patch-25/meeting-notes/2020-04-01.md) I think you can edit it.

(That, or using GitHub Desktop, or from the CLI).
Let me know if this helps!

**Comment by carolynvs** [comment]
Let me know when this is ready for review. It looked fine to me but maybe I am missing something?

**Comment by karenhchu** [comment]
Updated! Thanks for the help @radu-matei :) Ready to be merged.

**Review by radu-matei — APPROVED** [review]

**Pull request merged**
