### PR TITLE
Migrating the existing meeting notes from the hackmd over to files in…

### PR DESCRIPTION
**Pull request by karenhchu**
… the community repo

Signed-off-by: Karen Chu <karen.chu@microsoft.com>

### CODE REVIEW

**Comment by radu-matei** [comment]
I think the notes for this meeting are in the [`security-registry-wg` directory](https://github.com/cnabio/community/blob/master/meeting-notes/security-registry-wg/2020-02-26.md), although the recording URL is not there.

**Review by carolynvs — APPROVED** [review]
LGTM

**Review by carolynvs — CHANGES_REQUESTED** [review]
Oops, Radu is right, looks like these notes are in the wrong directory?

**Comment by carolynvs** [comment]
~@radu-matei Is there something wrong with the recording? I was able to view the recording linked from the document.~

UPDATED: After more coffee, I understand what you said. We don't need this PR to add a new set of notes. The notetaker already uploaded them to the security wg directory and all we need is a PR to add a link to the video to that existing document https://github.com/cnabio/community/blob/master/meeting-notes/security-registry-wg/2020-02-26.md

**Comment by carolynvs** [comment]
I apologize but I merged the other PR https://github.com/cnabio/community/pull/28 that made the same error. I forgot that we were putting notes in separate directories and didn't think to check for the existing one.

I'll submit a PR to fix what I merged in 1 sec.

**Comment by karenhchu** [comment]
I submitted a PR to update the Feb 26 agenda with the Youtube URL. I think we're good here. Can someone double check before I close this PR?

**Comment by carolynvs** [comment]
@karenhchu Yup, all set. Thanks and sorry for the confusion!

**Pull request closed without merging**
